### ISSUE TITLE
Root doesn't change own position

### ISSUE THREAD

**Issue by dgaszewski** [daniel-hauser/react-organizational-chart#1]
**Shortly**
The root item doesn't change its position when the tree is expanding.

**Bug description**
If you expand the tree downwards from the left side so the whole tree moves and change position to fit all expanded Children - except the root, it stays in own places and detaches from the whole tree.

**Comment by daniel-hauser** [comment]
Can you provide a codepen example?

**Comment by dgaszewski** [comment]
I'm not sure how I can import your Component in CodePen, but if you check for example https://github.com/staffannase/sample-org-chart from @staffannase (skip the login page and you will see a chart used with faker). After expanding from the left side the root is detached:

![Skärmklipp](https://user-images.githubusercontent.com/30286317/62043378-7d184f00-b200-11e9-9ab8-03b669dac5b5.PNG)

**Comment by daniel-hauser** [comment]
For now, the `react-organizational-chart` component does not look good in narrow containers.
A possible solution is to set `overflow-x: auto;` in the container style.

You are welcome to open a pull request if you wish to add this functionality

**Comment by Bopzor** [comment]
Hi!

First, thank you @daniel-hauser for this lib :)

I wanted to fix this on my project, but I notice that, since version `1.0.0`, `Tree` component does not accept `className`. (adding `display: flex` to root `ul` seems to do the trick).

It used to be typed as `TreeProps & TreeNodeProps`, so it works on versions prior to `1.1.0`.


Here are an example with version [`1.0.2`](https://codesandbox.io/s/react-organizational-chart-issue1-v102-uuinq)

and here an example with version [`1.1.0`](https://codesandbox.io/s/react-organizational-chart-issue1-v110-jletm?file=/src/StyledTreeExample.js).

Would you like me to open a PR that will allow adding `className` on `Tree` component?

**Comment by daniel-hauser** [comment]
@Bopzor 
> Would you like me to open a PR that will allow adding `className` on `Tree` component?

Sure, ill be happy to get a PR adding `display: flex` to the `Tree`

**Comment by Bopzor** [comment]
I noticed that `display: inline-block` also work. Do you have a preference between using `flex` or `inline-block`?

**Comment by Bopzor** [comment]
Hi again.

Can you please give me permission to push my branch `fix/rootNodePosition` so, I can open the PR?

![image](https://user-images.githubusercontent.com/26028196/95778734-019da300-0cc9-11eb-8480-47f9c7bc7be8.png)
